excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://gondylife.github.io
name: Godswill Okwara Blog
description: Wanna Learn? Then you at the right place. I tell you how i run my day and you learn from it.
author: gondylife
avatar: http://www.gravatar.com/avatar/d41d8cd98f00b204e9800998ecf8427e?s=120&d=mm&r=g
ga_domain: 
ga_tracking_id: 